title: "Hector Romo"
url: "http:localhost:4000"
# url: "www.hectorromo.com"
baseurl: ""
encoding: "utf-8"
markdown: "kramdown"
permalink: "pretty"

collections:
  projects:
    output: "true"
    permalink: "/project/:path/"

exclude: ['node_modules', 'package.json']