title: "Hector Romo"
#url: "http:localhost:4000"
url: "https://www.hectorromo.com"
baseurl: ""
encoding: "utf-8"
markdown: "kramdown"
permalink: "pretty"
version: 3.2.1

collections:
  projects:
    output: "true"
    permalink: "/:path/"

exclude: ['node_modules', 'package.json']